### ISSUE TITLE
Torosyan || Docker Support to the Project

### ISSUE THREAD

**Issue by jackijacki** [musheghtorosyan/compassprepschool.com#1]
We need to add Docker support to the project to streamline development, testing, and deployment. The goal is to create a Dockerfile that sets up the necessary environment and dependencies to run the application in a container. This will improve consistency across different environments and simplify onboarding for new developers.

Tasks:

- Create a Dockerfile for the project.
- Define necessary dependencies and configurations (e.g., base image, environment variables, ports, etc.).
- Test the Docker container to ensure the application runs correctly.
- Update documentation with Docker usage instructions.

**Comment by musheghtorosyan** [comment]
Please check this
```dockerfile
FROM php:8.1-apache

# Set the working directory
WORKDIR /var/www/html

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql mysqli

# Copy application files
COPY . .

# Expose port 80
EXPOSE 80

# Command to run Apache in the foreground
CMD ["apache2-foreground"]
```

```yaml
version: '3'
    services:
    app:
    build:
    context: .
    dockerfile: Dockerfile
    ports:
    - "8000:80"
    volumes:
    - .:/var/www/html

    db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: laravel
    MYSQL_USER: laravel_user
    MYSQL_PASSWORD: secret
 ```
